#!/bin/bash
#
# Sync Homebrew installations between Macs via Dropbox, including casks
#

BREW="/usr/bin/env brew"

DROPBOX="$HOME/Dropbox (Personal)/Apps/Homebrew"
TMPDIR="/tmp"

TAPS_FILENAME="brew-sync.taps"
BREWS_FILENAME="brew-sync.installed"
CASKS_FILENAME="brew-sync.casks"

LOCAL_TAPS="$TMPDIR/$TAPS_FILENAME"
LOCAL_BREWS="$TMPDIR/$BREWS_FILENAME"
LOCAL_CASKS="$TMPDIR/$CASKS_FILENAME"

DROPBOX_TAPS="$DROPBOX/$TAPS_FILENAME"
DROPBOX_BREWS="$DROPBOX/$BREWS_FILENAME"
DROPBOX_CASKS="$DROPBOX/$CASKS_FILENAME"

# Run brew to get any auto-updating out of the way
echo "Updating homebrew..."
$BREW update

# First get local package information
echo "Reading local settings..."
rm -f "$LOCAL_TAPS" "$LOCAL_BREWS" "$LOCAL_CASKS"
$BREW tap -1 > "$LOCAL_TAPS"
$BREW list -1 > "$LOCAL_BREWS"
$BREW cask list -1 > "$LOCAL_CASKS"

# Setup our Dropbox destination (if not there already)
mkdir -p "$DROPBOX"
touch "$DROPBOX_TAPS" "$DROPBOX_BREWS" "$DROPBOX_CASKS"

line_count() {
  cat "$1" | wc -l | tr -d ' '
}

# Install everything that's in the Dropbox settings but not locally
# Taps first
echo "Checking `line_count "$DROPBOX_TAPS"` taps..."
for tap in `cat "$DROPBOX_TAPS"`; do
  echo "$tap ..."
  grep "$tap" "$LOCAL_TAPS" >/dev/null && echo -n "." || echo "tap not installed: $tap\n"
  $BREW tap $tap
done
echo

# Then brews
echo "Checking `line_count "$DROPBOX_BREWS"` packages..."
for package in `cat "$DROPBOX_BREWS"`; do
  echo $package ...
  grep "$package" "$LOCAL_BREWS" >/dev/null && echo -n "." || echo "package not installed: $package\n" # TODO install it
  # [ "$?" != "0" ] && $BREW install ${PACKAGE}
  $BREW install $package
done
echo

# Then casks
echo "Checking `line_count "$DROPBOX_CASKS"` casks..."
for cask in `cat "$DROPBOX_CASKS"`; do
  echo $cask ...
  grep "$cask" "$LOCAL_CASKS" >/dev/null && echo -n "." || echo "cask not installed: $cask\n"
  # [ "$?" != "0" ] && $BREW cask install ${CASK}
  $BREW cask install $cask
done
echo

# Combine our local settings with our Dropbox settings
echo "Merging local settings with Dropbox settings..."
[ -e "$DROPBOX_TAPS" ]  && cat "$DROPBOX_TAPS"  >> $LOCAL_TAPS
[ -e "$DROPBOX_BREWS" ] && cat "$DROPBOX_BREWS" >> $LOCAL_BREWS
[ -e "$DROPBOX_CASKS" ] && cat "$DROPBOX_CASKS" >> $LOCAL_CASKS

# Then merge, de-dupe and put that list back in Dropbox
echo "Saving combined settings to Dropbox..."
cat $LOCAL_TAPS  | sort | uniq > "$DROPBOX_TAPS"
cat $LOCAL_BREWS | sort | uniq > "$DROPBOX_BREWS"
cat $LOCAL_CASKS | sort | uniq > "$DROPBOX_CASKS"

# That's it!
echo "All done."
